### ISSUE TITLE
is the comment accurate?

### ISSUE THREAD

**Issue by aceeric** [operator-framework/operator-sdk-samples#126]
Please see: https://github.com/operator-framework/operator-sdk-samples/blob/66156b18ed3dbda304de7db28f0071bd7c9e9e60/go/memcached-operator/pkg/controller/memcached/memcached_controller.go#L124

The comment indicates that the request is being re-queued in order to "to ensure the deployment size is the same as the spec" -- but is that really why the request is being re-queued? Referring to:

https://groups.google.com/forum/#!topic/operator-framework/zxlvESoMSh8

A more reasonable explanation seems to be that the request is being re-queued in order to update the status. If that's correct, then the comment should be modified to agree with the actual intent of the code.

**Comment by camilamacedo86** [comment]
Hi @aceeric, 

The reconcile function is responsible for synchronizing the resources and their specifications according to the business logic implemented on them. **In this way, it works like a loop**, and it does not stop until all conditionals match its implementation. The following is pseudo-code with an example that clarifies it.

```go
reconcile App {

   // Check if a Deployment for the app exists, if not create one
   // If has an error, then go to the beginning of the reconcile
   if err != nil {
       return reconcile.Result{}, err 
   } 
   
   // Check if a Service for the app exists, if not create one 
   // If has an error, then go to the beginning of the reconcile
   if err != nil {
       return reconcile.Result{}, err 
   }  

   // Looking for Database CR/CRD 
   // Check the Database Deployments Replicas size
   // If deployment.replicas size != cr.size, then update it
   // Then, go to the beginning of the reconcile
   if err != nil {
       return reconcile.Result{Requeue: true}, nil
   }  
   ...
   
   // If it is at the end of the loop, then:
   // All was done successfully and the reconcile can stop  
   return reconcile.Result{}, nil

}
```
From : https://developers.redhat.com/blog/2019/10/04/getting-started-with-golang-operators-by-using-operator-sdk/

in this way, see that:

```
// NOTE: that the requeue is made with the purpose to provide the deployment object for the next step to ensure the deployment size is the same as the spec.
// Also, you could GET the deployment object again instead of requeue if you wish. See more over it here: https://godoc.org/sigs.k8s.io/controller-runtime/pkg/reconcile#Reconciler
```

We are in the example doing the re-queue for we are able to GET the Deployment that was just created and then, otherwise we are unable to check its size. Another way to achieve the same, as described in the comment, would be by using the client-go to GET the deployment before we do the check: 

```
// Ensure the deployment size is the same as the spec
	size := memcached.Spec.Size
	if *deployment.Spec.Replicas != size {
		deployment.Spec.Replicas = &size
		err = r.client.Update(context.TODO(), deployment)
		if err != nil {
			reqLogger.Error(err, "Failed to update Deployment.", "Deployment.Namespace", deployment.Namespace, "Deployment.Name", deployment.Name)
			return reconcile.Result{}, err
		}
	}
```

We need to get its latest state from the cluster before check its size which will be made in the next round of the loop. See: 

```go
// Check if the Deployment already exists, if not create a new one
	deployment := &appsv1.Deployment{}
	err = r.client.Get(context.TODO(), types.NamespacedName{Name: memcached.Name, Namespace: memcached.Namespace}, deployment)

```

In this way, I am closing this one since I believe that the above information clarifies the example. However, feel free to ping us if you think that it should be re-opened for any reason.
