### ISSUE TITLE
Use same memcached image across all samples?

### ISSUE THREAD

**Issue by geerlingguy** [operator-framework/operator-sdk-samples#155]
I noticed the Ansible and Go samples use `docker.io/memcached:1.4.36-alpine`, whereas the Helm sample uses `memcached:1.5.20`.

I am overriding the image for the Helm deployment to use the same image for comparison purposes, but it seems like it would be useful to standardize on one memcached image/version/format for all three samples.

**Comment by camilamacedo86** [comment]
Helm uses the image version from the helm-chart.

**Comment by geerlingguy** [comment]
@camilamacedo86 - Ah, I didn't realize that.

I wonder then, could we update the other two operators to make `image` be in the `spec`? That way at least in my use case, I could set it in one place and use that for all three, for consistency.

Some of the issues I'm filing are for my specific benchmarking use case, but in general, I think it would be nice to try to get some more feature parity among the three samples—there are a few small things where it seems each one does something different.

**Comment by camilamacedo86** [comment]
Hi @geerlingguy, 

Would you like to help with that? I think it for us would be a really low priority since it shows not make a really diff, however, if you be able to contribute with the project we can help by reviewing and get merged your pr.  

So, it means: 

- Update the script for ansible. See; https://github.com/operator-framework/operator-sdk-samples/blob/master/ansible/.generate/role_main.yml#L28
- Update the script for Go. See: https://github.com/operator-framework/operator-sdk-samples/blob/master/go/.generate/gen-go-sample.sh#L111
- Regenerate both via script. 

WDYT?

**Comment by camilamacedo86** [comment]
hi @geerlingguy, 

Also, see that the idea is to deprecate this one. More info: https://github.com/operator-framework/operator-sdk-samples/pull/163.  

I am closing this one. However, please feel free to raise issues against the SDK repo if you need.
