### ISSUE TITLE
valut-operator sample cannot be built

### ISSUE THREAD

**Issue by nak3** [operator-framework/operator-sdk-samples#46]
### issue

Currently, valut-operator sample cannot be built. 

### operator-sdk version

~~~
$ operator-sdk --version
operator-sdk version v0.1.1+git
~~~

### steps to produce

Just followed steps in README.

~~~
$ mkdir $GOPATH/src/github.com/operator-framework
$ cd $GOPATH/src/github.com/operator-framework
$ git clone https://github.com/operator-framework/operator-sdk-samples.git
$ cd operator-sdk-samples/vault-operator
$ operator-sdk build $IMAGE
~~~

Then, get following error.

~~~
$ operator-sdk build $IMAGE
FATA[0000] must run command in project root dir: project structure requires ./build/Dockerfile 
~~~

**Comment by camilamacedo86** [comment]
Hi @nak3, 

Really thank you for your collab with 🥇. 

This sample is outdated. So, since is hard to keep maintained many samples we decided to move forward just with the Memcached ones. Because of this, I am closing this one. Shows that is an outdated issue too. However, please feel free to re-open if you think that is required.
